# Generated by Django 2.1.4 on 2019-01-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_form',
            field=models.FileField(blank=True, null=True, upload_to='activation_forms/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cost_center',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cost_center_end_date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institution',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='customuser',
            name='net_id',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='supervisor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='training_form',
            field=models.FileField(blank=True, null=True, upload_to='training_forms/'),
        ),
    ]
