# Generated by Django 2.1.4 on 2019-01-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190109_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cost_center_end_date',
            field=models.DateField(blank=True, max_length=30),
        ),
    ]
