# Generated by Django 2.1.4 on 2019-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cas', models.CharField(max_length=20)),
                ('container_size', models.CharField(max_length=20)),
                ('number_of_containers', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
                ('cabinet_number', models.IntegerField()),
                ('owner', models.CharField(max_length=50)),
                ('msds', models.FileField(blank=True, null=True, upload_to='msds/')),
            ],
        ),
    ]
